<section class="mt-3 card card-body">
    <h1>Gerenciar Alunos</h1>

    <div>
        <a href="/alunos/novo" class="btn btn-outline-info">Novo Aluno</a>
        <a href="/alunos/relatorio" target="_blank" class="btn btn-outline-info">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Perfil</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($users ?? [] as $user){
                    echo "
                    <tr>
                        <td>{$user->id}</td>
                        <td>{$user->nome}</td>
                        <td>{$user->matricula}</td>
                        <td>{$user->cpf}</td>
                        <td>{$user->email}</td>
                        <td>
                            <a href='/usuarios/editar?id={$user->id}' class='btn btn-outline-warning btn-sm'>Editar</a>
                            <a href='/usuarios/excluir?id={$user->id}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                        </td>
                    </tr>";
                }
            ?>
        </tbody>
    </table>
</section>