<section class="mt-3 card card-body">
    <h1>Novo Usuario</h1>
    
    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control mb-3" >

                <label for="email">Email</label>
                <input type="text" name="email" id="email" class="form-control mb-3">

                <label for="senha">Senha</label>
                <input type="password" name="senha" id="senha" class="form-control mb-3">
                
                <label for="perfil">Perfil </label>
                <select name="perfil" id="perfil">
                    <option value="normal">Normal</option>
                    <option value="admin">Administrador</option>
                </select>

                <button class="btn btn-primary">Pronto</button>

            </form>
        </div>
        <div class="col"></div>
    </div>
</section>