<?php
    $aluno=$dados[0];
    
?>

<section class="mt-3 card card-body">
<h1>Editar</h1>

<div class="row">
    <div class="col">
        <form action="/alunos/editar" method="POST">
            <label for="nome">Nome</label>
            <input type="text" name="nome" id="nome" class="form-control mb-3" value="<?php echo $aluno->nome?>">

            <label for="email">Email</label>
            <input type="text" name="email" id="email" class="form-control mb-3" value="<?php echo $aluno->email?>">

            <label for="cpf">Cpf</label>
            <input type="text" name="cpf" id="cpf" class="form-control mb-3" value="<?php echo $aluno->cpf?>">
            
            <label for="nascimento">Data Nascimento</label>
            <input type="date" name="nascimento" id="nascimento" class="form-control mb-3" 
            value="<?php date("Y-m-d", strtotime($aluno->dataNascimento)); ?>">

            <label for="genero">Genero</label>
            <input type="text" name="genero" id="genero" class="form-control mb-3" value="<?php echo $aluno->genero?>">

            <button class="btn btn-primary">Pronto</button>

        </form>
    </div>
    <div class="col"></div>
</div>
</section>
