
<section class="mt-3 card card-body">
    <h1>Novo Curso</h1>
    
    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control mb-3" >

                <label for="cargaHoraria">Carga Horaria</label>
                <input type="text" name="cargaHoraria" id="cargaHoraria" class="form-control mb-3">

                <label for="descricao">Descrição</label>
                <input type="text" name="descricao" id="descricao" class="form-control mb-3">

                <label for="categoria">Categoria id</label>
                <select name="categoria" id="categoria" class="form-control mb-3">
                    <?php
                        foreach($categorias as $categoria){
                            echo "
                                <option value='{$categoria->id}'>{$categoria->nome}</option>
                            ";
                        }
                    ?>
                </select>

                <button class="btn btn-primary">Pronto</button>

            </form>
        </div>
        <div class="col"></div>
    </div>
</section>