
<section class="mt-3 card card-body">
    <h1>Novo Curso</h1>
    
    <div class="row">
        <div class="col">
            <form action="/curso/cadastrar" method="POST">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control mb-3" >

                <label for="cargaHoraria">Carga Horaria</label>
                <input type="text" name="cargaHoraria" id="cargaHoraria" class="form-control mb-3">

                <label for="descricao">Descrição</label>
                <input type="text" name="descricao" id="descricao" class="form-control mb-3">
                
                <label for="status">Status </label>
                <input type="text" name="status" id="status" class="form-control mb-3">

                <label for="categoria_id">Categoria id</label>
                <input type="text" name="categoria_id" id="categoria_id" class="form-control mb-3">

                <button class="btn btn-primary">Pronto</button>

            </form>
        </div>
        <div class="col"></div>
    </div>
</section>